pocketsquare/config/routes.rb
Rails.application.routes.draw do
  # root route
  # root to: "home#index"

  root :to => "home#index"

  # users routes

  get "/users" => "users#index"

  get "/users/new" => "users#new"

  post "/users" => "users#create"

  get "/user/login" => "users#login"

  post "/user/login" => "users#process_login"



  # venues routes "controller#action"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  # resources implementation
  resources :users
  resources :sessions

  resources :venues do
    collection do
      get "search"
    end
  end
  #get "venues/search" => "venues#search"

end

pocketsquare/app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :venue
end

pocketsquare/app/models/user.rb
class User < ActiveRecord::Base
  # include BCrypt
  has_secure_password

  # "Users" connected to "Venues" through join table "Favorites"
  has_many :venues, through: :favorites
  # Allows to call method .favorites on any user
  has_many :favorites

  # consistency on all email fields
  before_validation :downcase_email

  # validation presence and confirmation
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :user_email

  # no duplicates on db
  validates :user_email, uniqueness: true

  def downcase_email
    self.user_email = user_email.downcase
  end

end

pocketsquare/app/models/venue.rb
class Venue < ActiveRecord::Base
  # "Venues" connected to "Users" through join table "Favorites"
  has_many :users, through: :favorites
  # Allows to call method .favorites on any user
  has_many :favorites

  # where do these data validations should go in order to work? models or controllers?
  validates_presence_of :keyword, :zip_code
  validates_numericality_of   :zip_code
                              :only_integer => true
                              :allow_nil => false

  include FoursquareHelper

  # explores for food near GA West and returns a list of the names of the food venues
  def self.explore
    venues = Foursquare.explore_near("food", {latitude: 40.739848, longitude: -73.989567})

    venues.map do |venue|
      venue["venue"]["name"]
    end
  end



end

pocketsquare/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

# information restriction
  def require_login
    if current_user
      current_user
    else
      redirect_to root_path
    end
  end
  # helper required
  helper_method :current_user

  private
  # a normally private instance variable
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

pocketsquare/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

pocketsquare/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(user_email: params.fetch(:user_email))
    success = user.authenticate(params[:password])
    # success is ActiveRecord
    if success
      session[:user_id] = user.id
      redirect_to root_url, :notice => "You are now logged in!"
    else
      # display error message & renew
      flash.now.alert = "Error: Invalid email or password"
      render "new"
    end
  end

  # only way to log out current user
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

pocketsquare/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new (user_attributes)
    if @user.save
      redirect_to root_url, :notice => "You have been signed up!"
    else
      render "new"
    end

  end

  private

  def user_attributes
    params.require(:user).permit(:user_name, :user_email, :password, :password_confirmation)
  end
end

pocketsquare/app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  include FoursquareHelper

  before_action :require_login

  def index
    # @venues = Venue.all
    puts "Index method test print"
  end

  def search

    # validates :keyword, :zip_code, presence: true
    # validates :zip_code, length: { is: 5 }, numericality: { only_integer: true }
    # if params[:zip_code].present? && params[:zip_code].to_i.valid?
        # binding.pry
      @search_results = Foursquare.explore_near(params[:keyword], {zip_code: params[:zip_code], radius: 1600})
      # @search_results = Foursquare.explore_near(params[:keyword], {latitude: 40.739848, longitude: -73.989567})

      @search_results = @search_results.map do |venue|
        {name: venue["venue"]["name"], rating: venue["venue"]["rating"]}
      end

      @search_results = @search_results.uniq.sort {|x,y| y[:rating] <=> x[:rating]}.slice(0..9)
      render :index

    # else

    # end
  end

  # display specific venue based on an ID search
  def show
    @Venue = Venue.find(params[:id])
  end
end

pocketsquare/app/helpers/application_helper.rb
module ApplicationHelper
end

pocketsquare/app/helpers/foursquare_helper.rb
module FoursquareHelper
  class Foursquare
    @@url_base      = "https://api.foursquare.com/v2/venues/"
    @@client_id     = Rails.application.secrets.foursquare_client_id
    @@client_secret = Rails.application.secrets.foursquare_client_secret

    def self.build_url_for_ll(action, query, latitude, longitude)
      "#{@@url_base}#{action}?ll=#{latitude},#{longitude}&client_id=#{@@client_id}&client_secret=#{@@client_secret}&v=20140517&query=#{query}"
    end

    def self.build_url_for_zip(action, query, zip_code, radius)
      "#{@@url_base}#{action}?near=#{zip_code}&radius=#{radius}&client_id=#{@@client_id}&client_secret=#{@@client_secret}&v=20140517&query=#{query}"
    end

    def self.call_api_for(action, query, location)
      if location[:zip_code].nil? # TODO clean this up a little, it's too implementation-dependent
        JSON.parse(HTTParty.get(Foursquare.build_url_for_ll(action, query, location[:latitude], location[:longitude])).body)
      else
        JSON.parse(HTTParty.get(Foursquare.build_url_for_zip(action, query, location[:zip_code], location[:radius])).body)
      end
    end

    def self.explore_near(query, location)
      Foursquare.call_api_for("explore", query, location)["response"]["groups"][0]["items"]
    end
  end
end

pocketsquare/app/views/favorites/index.html.erb
<h3>Favorite Venues</h3>

<ul>
  <% @venues.each do |venue| %>
  <!-- link_to venue.venue_name, "venue/- - -" -->
    <p><ul>Name: <%= venue.name %></ul></p>
    <p><ul>Address: <%= venue.venue_address %></ul></p>
    <p><ul>Twitter: <%= venue.venue_twitter %></ul></p>
  <% end %>

</ul>

pocketsquare/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>

  <title>PocketSquare!</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <% if current_user %>
    <p>Welcome back, <%= current_user.user_name %>!</p>
    <!-- (<%= current_user.id %>) -->
  <% else %>
  <% end %>

  <h1>PocketSquare</h1>
  <h3>Find your next favorite spot</h3>

  <%= link_to "New Search", "/venues" %> | <%= link_to "My Pocket", "/favorites" %> | <%= link_to "[Spy Mode]", "/spy" %>

  <div id="user_nav">
    <% if current_user %>

      <p>Now logged in as <%= current_user.user_email %> | <%= link_to "Log out", log_out_path %></p>
      <!-- <p><%= link_to "Begin your search", "/venues" %></p> -->

    <% else %>

      <%= link_to "Sign up", sign_up_path %> or
      <%= link_to "Log in", log_in_path %>

    <% end %>

  </div>




<%= yield %>

</body>

</html>

pocketsquare/app/views/users/login.html.erb
<!-- login form process -->
<%= form_tag do %>

  <%= text_field_tag "user_email", nil, { placeholder: "email" } %>
  <%= password_field_tag "password", nil, { placeholder: "password" } %>
  <%= submit_tag "Login" %>

<% end %>

pocketsquare/app/views/users/new.html.erb
<h3>Sign up for an account</h3>

<!-- form errors and validation -->
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form error!</h2>
      <ul>
      <% for message in @user.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :Name %><br />
    <%= f.text_field :user_name %>
  </p>
  <p>
    <%= f.label :Email %><br />
    <%= f.text_field :user_email %>
  </p>
  <p>
    <%= f.label :Password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :Password_Confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>

<!-- submit button for db access -->
  <p class="button"><%= f.submit %></p>
<% end %>

pocketsquare/app/views/venues/index.html.erb
<h3>Search For New Pocket Favorites</h3>
<%= form_tag search_venues_path, method: "get" do %>
  <p>
    <%= label_tag :keyword, "Search Keywords" %><br />
    <%= text_field_tag :keyword %>
  </p>
  <p>
    <%= label_tag :zip_code %><br />
    <%= text_field_tag :zip_code %>
  </p>

<!-- submit button for api query -->
  <p class="button"><%= submit_tag "Let's Go!" %></p>
<% end %>

<% unless @search_results.nil? %>
  <ul>
    <% @search_results.each do |venue| %>
      <li><strong><%= venue[:name] %></strong>, Rated as <%= venue[:rating] %></li>
    <% end %>
  </ul>
<% end %>

pocketsquare/app/views/venues/show.html.erb
<h3><%= @venue.name %></h3>
<ul>
  <p><li><%= @venue.venue_phone %></li></p>
  <p><li><%= @venue.venue_address %></li></p>
  <p><li><%= @venue.venue_zip %></li></p>
  <p><li><%= @venue.venue_twitter %></li></p>
</ul>

<!-- print email and id of user logged in -->
<!-- <%= current_user.user_email %> <%= current_user.id %> -->

<!-- provide a button to go back -->
<%= link_to "Go back", venues_path %>